# Generated by Django 2.2.6 on 2019-10-31 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.TextField(max_length=2000)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('votes_total', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, default='product_pics/default.jpg', null=True, upload_to='product_pics')),
                ('icon', models.ImageField(blank=True, default='product_pics/default.jpg', null=True, upload_to='product_pics')),
                ('body', models.TextField(max_length=2000)),
                ('hunter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
